USE PLANNING_TOOL;

CREATE TABLE PHASE (
	ID_PHASE int NOT NULL auto_increment,
    TITEL varchar(255) NOT NULL,
    SORTIERUNG INT NOT NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_PHASE)
);