USE PLANNING_TOOL;

CREATE TABLE STATUS (
	ID_STATUS int NOT NULL auto_increment,
    TITEL varchar(255) NOT NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_STATUS)
);