USE PLANNING_TOOL;

CREATE TABLE PERSON (
	ID_PERSON int NOT NULL auto_increment,
    VORNAME varchar(255) NULL,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NULL,
    TELEFON VARCHAR(255) NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_PERSON)
);