USE PLANNING_TOOL;

CREATE TABLE KUNDE (
	ID_KUNDE int NOT NULL auto_increment,
    BEZEICHNUNG varchar(255) NOT NULL,
    ID_PERSON INT NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_KUNDE),
    FOREIGN KEY (ID_PERSON) REFERENCES PERSON(ID_PERSON)
);