USE PLANNING_TOOL;

CREATE TABLE PROJEKT (
	ID_PROJEKT int NOT NULL auto_increment,
    TITEL varchar(255) NOT NULL,
    ID_KUNDE INT NULL,
    VON DATE NULL,
    BIS DATE NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_PROJEKT),
    FOREIGN KEY (ID_KUNDE) REFERENCES KUNDE(ID_KUNDE)
);