USE PLANNING_TOOL;

CREATE TABLE PHASE_PROJEKT (
	ID_PHASE_PROJEKT int NOT NULL auto_increment,
    ID_PHASE INT NOT NULL,
    ID_PROJEKT INT NOT NULL,
    VON DATE NULL,
    BIS DATE NULL,
    MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_PHASE_PROJEKT),
    FOREIGN KEY (ID_PHASE) REFERENCES PHASE(ID_PHASE),
    FOREIGN KEY (ID_PROJEKT) REFERENCES PROJEKT(ID_PROJEKT)
);