USE PLANNING_TOOL;

CREATE TABLE TICKET (
	ID_TICKET int NOT NULL auto_increment,
    TITEL VARCHAR(255) NOT NULL,
    BESCHRIEB VARCHAR(4000) NOT NULL, 
    TERMIN DATE NOT NULL,
    PRIORITAET INT NOT NULL,
    ID_STATUS INT NOT NULL,
    ID_PROJEKT INT NULL,
    ID_KUNDE INT NULL,
	MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_TICKET),
    FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID_STATUS),
    FOREIGN KEY (ID_PROJEKT) REFERENCES PROJEKT(ID_PROJEKT),
    FOREIGN KEY (ID_KUNDE) REFERENCES KUNDE(ID_KUNDE)
);