USE PLANNING_TOOL;

CREATE TABLE MITARBEITER (
	ID_MITARBEITER int NOT NULL auto_increment,
    ID_PERSON INT NOT NULL,
    BENUTZERNAME VARCHAR(50) NOT NULL,
    PASSWORT VARCHAR(255) NOT NULL, 
    AKTIV TINYINT(1) NOT NULL,
	MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_MITARBEITER),
    FOREIGN KEY (ID_PERSON) REFERENCES PERSON(ID_PERSON)
);