USE PLANNING_TOOL;

CREATE TABLE PROJEKT_MITARBEITER (
	ID_PROJEKT_MITARBEITER int NOT NULL auto_increment,
    ID_MITARBEITER INT NOT NULL,
    ID_PROJEKT INT NOT NULL,
	MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_PROJEKT_MITARBEITER),
    FOREIGN KEY (ID_MITARBEITER) REFERENCES MITARBEITER(ID_MITARBEITER),
    FOREIGN KEY (ID_PROJEKT) REFERENCES PROJEKT(ID_PROJEKT)
);