USE PLANNING_TOOL;

CREATE TABLE PLANUNG (
	ID_PLANUNG int NOT NULL auto_increment,
    ID_MITARBEITER INT NOT NULL,
    ID_TICKET INT NOT NULL,
    ID_ANSPRECHSPERSON INT NULL,
    ID_PHASE INT NOT NULL,
    VON DATE NOT NULL,
    BIS DATE NOT NULL,
    SITZUNG TINYINT(1),
	MUTIARTAM DATETIME NOT NULL,
    MUTIERTVON VARCHAR(50) NOT NULL,
    ID_UNIQUE NUMERIC(20, 0) NOT NULL,
    PRIMARY KEY (ID_PLANUNG),
    FOREIGN KEY (ID_MITARBEITER) REFERENCES MITARBEITER(ID_MITARBEITER),
    FOREIGN KEY (ID_TICKET) REFERENCES TICKET(ID_TICKET),
    FOREIGN KEY (ID_ANSPRECHSPERSON) REFERENCES ANSPRECHSPERSON(ID_ANSPRECHSPERSON),
    FOREIGN KEY (ID_PHASE) REFERENCES PHASE(ID_PHASE)
);